name: Pull request to dev

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  lintCheckAndUnitTests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew check --stacktrace
      
    - uses: actions/upload-artifact@v4
      with:
        name: test-report.html
        path: app/build/reports/tests/testDebugUnitTest/index.html
        
    - uses: actions/upload-artifact@v4
      with:
        name: lint-results.html
        path: app/build/reports/lint-results-debug.html
